import React from 'react'

export default {
  name: 'Casey Sullivan',
  position: 'Skilled UI/UX Developer',
  location: 'South Burlington, VT',
  abstract: `I'm a UI/UX developer with nearly 20 years of professional success. I'm designer that sweats 
             the small stuff. I like to take complex systems and make them easy and intuitive. I have had experiences 
             with many different technologies and in several disparate industries.`,
  personal:
    'I enjoy games, board more than video these days. I like death metal and pro wrestling. I love riding bikes. I share a home office with a corgi named Gabe. He likes cheese.',
  email: 'casey.sullivan@gmail.com',
  repoUrl: 'https://github.com/yesacs/resume',
  education: {
    degree: 'B.S., Computer Science',
    school: "Saint Michael's College",
    location: { city: 'Colchester', state: 'VT' },
    duration: { start: 2000, end: 2004 },
  },
  jobs: [
    {
      title: 'Head of Product Design',
      company: 'FRIKINtech',
      industry: 'Car Dealership Operations',
      duration: { start: 2018 },
      location: { city: 'Williston', state: 'VT' },
      current: true,
      duties: [
        'Responsible for the design, development and maintence of illumiQUOTE, a system allowing car shoppers to generate penny-perfect payments including equity, fees, taxes and rebates using React/Redux/Sass',
        'Designed and developed WEBSITEiQ, an embedded lightweight widget to automatically show car payments on dealer websites using vanilla JS/CSS',
        "Designed email templates sent to customers on dealers' behalf to intice their service customers to shop with their equity",
        'Wrote and maintained  scripts to enforce best practices with regard to build and deploy to AWS',
        'Worked with OEMs to ensure brand compliance',
      ],
    },
    {
      title: 'User Experience Developer',
      company: 'Pwnie Express',
      industry: 'Cyber Security',
      location: { city: 'Burlingon', state: 'VT' },
      duration: { start: 2015, end: 2018 },
      duties: [
        'Primary UX designer of Pulse 2.0, a cloud-based dashboard used by security professionals to monitor threats on their corporate networks using React/Redux/Sass',
        'Created exective reports designed to info C-Levels about threat severity and mitigation succes on their networks',
        "Worked on embedded web UIs for admintration of Pwnie's physical sensor hardware",
        'Maintained legacy Pulse, a previous version, using Ember.js ',
        'Attended Black Hat/Defcon as a vendor to demo products',
      ],
    },
    {
      title: 'User Interface Developer',
      company: 'Dealer.com',
      industry: 'Car Dealership Marketing and Ops',
      location: { city: 'Burlingon', state: 'VT' },
      duration: { start: 2010, end: 2015 },
      duties: [
        "UI/UX developer and designer for CRM, Dealer.com's first dealer ops solution",
        'Designed and developed the Dealer.com Pencil Tool, a realtime car payment engine',
        'Developed embedable js apps designed to augment existing apps without backend integrations',
        'Met with our dealership customers to demo beta features and collect feedback',
        'Built internal CRM for in-house sales teams using Grails/jQuery',
      ],
    },
    {
      title: 'Interactive Developer',
      company: 'Propeller Media Works',
      industry: 'Custom Website Design and Development',
      location: { city: 'Burlingon', state: 'VT' },
      duration: { start: 2009, end: 2010 },
      duties: [
        'Worked with clients and designers to build and deploy custom websites using PHP and CSS',
        'Implemented customized e-commerce solutions for clients to sell online using Magento',
        'Built proof-of-concept next-gen CMS systems using Ruby on Rails',
      ],
    },
    {
      title: 'Manager Software + Analytics',
      company: 'EpikOne',
      industry: 'Google Analytics Consulting and Marketing',
      location: { city: 'Burlingon', state: 'VT' },
      duration: { start: 2007, end: 2009 },
      duties: [
        'Lead Ruby on Rails developer for one of the premier Google Analytics Authorized Consultancies',
        'Led development of SiteScan, a tool to verofy corrent GA installation on websites',
        'Led development of AnalyticsView, a pre-GA api data aggregator and report generator',
        'Led development of DigitalMIDI, a marketing communications dashboard for enterprise',
        'Extensive development using the Google Analytics API',
      ],
    },
    {
      title: 'HTML Production',
      company: 'Bluehouse Group',
      location: { city: 'Richmond', state: 'VT' },
      duration: { start: 2005, end: 2007 },
      duties: [
        'Developer of standards-based HTML and CSS, and PHP sites ranging from simple brochure sites to high-end e-commerce',
        'Web site production, development, and maintenance of over 30 sites',
        'Translation of designs from Photoshop into HTML and CSS',
        'Research of new technologies for use on future projects, such as Ajax and Ruby on Rails',
        'Helped develop Content Creator, a CMS system for sites that allows clients to build out the content of a site themselves',
      ],
    },
  ],
  skills: {
    React: 10,
    Redux: 9,
    jQuery: 10,
    Knockout: 10,
    Parcel: 9,
    Lodash: 10,
    CommonJS: 8,
    Jest: 7,
    HTML: 10,
    CSS3: 10,
    'Scss/Sass': 9,
    PHP: 6,
    HTMX: 7,
    Clojure: 5,
    'Responsive Design': 8,
    'Mobile-First Design': 8,
    'Scrum Agile/SAFe': 7,
  },
}
